name: Deploy to Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import streamlit; print('Streamlit version:', streamlit.__version__)"
        python -c "import pandas; print('Pandas version:', pandas.__version__)"
    
    - name: Build Docker image
      run: docker build -t streamlit-app .
    
    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 8501:8501 streamlit-app
        sleep 10
        curl -f http://localhost:8501 || exit 1
        docker stop test-container
        docker rm test-container
